### ISSUE TITLE
Add LICENCE File

### ISSUE THREAD

**Issue by notkurt** [OnTrack-UG-Squad/speaker-verification-api#5]
Add a licence file to the project.

**Comment by namvnn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add LICENCE](https://trello.com/c/NIoQZIQT/150-add-licence)

**Comment by namvnn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add LICENCE](https://trello.com/c/NIoQZIQT/150-add-licence)
